/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.*;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.util.regex.Pattern;

/**
 *
 * @author Leonidas
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_contenedor = new javax.swing.JPanel();
        Pnl_input = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_url = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Pnl_contarbol = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Pnl_arbol = new javax.swing.JPanel();
        Pnl_output = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pnl_contenedor.setBackground(new java.awt.Color(100, 112, 108));
        Pnl_contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_input.setBackground(new java.awt.Color(147, 83, 71));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 153));
        jLabel1.setText("HTML Tree");
        jLabel1.setToolTipText("");

        txt_url.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txt_url.setBorder(null);

        jLabel2.setBackground(new java.awt.Color(255, 204, 153));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 153));
        jLabel2.setText("URL: ");

        jLabel3.setBackground(new java.awt.Color(100, 112, 108));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Generar árbol");
        jLabel3.setToolTipText("");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout Pnl_inputLayout = new javax.swing.GroupLayout(Pnl_input);
        Pnl_input.setLayout(Pnl_inputLayout);
        Pnl_inputLayout.setHorizontalGroup(
            Pnl_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_inputLayout.createSequentialGroup()
                .addGroup(Pnl_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_inputLayout.createSequentialGroup()
                        .addGroup(Pnl_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl_inputLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Pnl_inputLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(Pnl_inputLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Pnl_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_url)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        Pnl_inputLayout.setVerticalGroup(
            Pnl_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_inputLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_url, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pnl_contenedor.add(Pnl_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 388));

        Pnl_contarbol.setBackground(new java.awt.Color(237, 233, 206));
        Pnl_contarbol.setLayout(new javax.swing.BoxLayout(Pnl_contarbol, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setBackground(new java.awt.Color(237, 233, 206));

        Pnl_arbol.setBackground(new java.awt.Color(237, 233, 206));

        javax.swing.GroupLayout Pnl_arbolLayout = new javax.swing.GroupLayout(Pnl_arbol);
        Pnl_arbol.setLayout(Pnl_arbolLayout);
        Pnl_arbolLayout.setHorizontalGroup(
            Pnl_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        Pnl_arbolLayout.setVerticalGroup(
            Pnl_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(Pnl_arbol);

        Pnl_contarbol.add(jScrollPane1);

        Pnl_contenedor.add(Pnl_contarbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 11, 690, -1));

        Pnl_output.setBackground(new java.awt.Color(199, 173, 136));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout Pnl_outputLayout = new javax.swing.GroupLayout(Pnl_output);
        Pnl_output.setLayout(Pnl_outputLayout);
        Pnl_outputLayout.setHorizontalGroup(
            Pnl_outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_outputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        Pnl_outputLayout.setVerticalGroup(
            Pnl_outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_outputLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Pnl_contenedor.add(Pnl_output, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 896, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments 
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>
        URL u = null;

        try {
            u = new URL("https://www.emuparadise.me/");
            ValidarURL(u);
        } catch (MalformedURLException ex) {
            System.out.println("URL Inválida");;
        }

       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });

    }

    public static void ValidarURL(URL url) throws IOException {
        boolean sw = false;
        try {
            URLConnection uc = url.openConnection();
            uc.connect();
            sw = true;
        } catch (IOException ex) {
            System.out.println("No se pudo establecer la conexión");
        }
        if (sw) {
            File f = new File("h.txt"),patron = new File("patron.txt"),prueba = new File("prueba.txt");
            
            BufferedWriter bw = new BufferedWriter(new FileWriter(f));
            BufferedReader br = new BufferedReader(new FileReader(prueba)),br2 = new BufferedReader(new FileReader(patron));
            String htmlformat = br2.readLine();
            br2.close();
            Pattern p = Pattern.compile(htmlformat,Pattern.MULTILINE);
            Matcher m;
            m = p.matcher(br.readLine());
            String s = null;
            while ((s = br.readLine()) != null) {
                m = p.matcher(s);
                if (m.find()) {
                    bw.write(m.group());
                    System.out.println("GROUP: "+m.group());
                    bw.newLine();
                }

            }
            
           
            try {
                bw.close();
                br.close();
            } catch (IOException ex) {
                Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("Holi");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pnl_arbol;
    private javax.swing.JPanel Pnl_contarbol;
    private javax.swing.JPanel Pnl_contenedor;
    private javax.swing.JPanel Pnl_input;
    private javax.swing.JPanel Pnl_output;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txt_url;
    // End of variables declaration//GEN-END:variables
}
